
--DROP TABLE public.requests CASCADE;
--DROP TABLE public.bookings CASCADE;
--DROP TABLE public.comments CASCADE;
--DROP TABLE public.items CASCADE;
--DROP TABLE public.users CASCADE;


CREATE TABLE IF NOT EXISTS users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
	name varchar NULL,
	email varchar NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT users_unique UNIQUE (email),
	CONSTRAINT users_unique123 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	description varchar NULL,
	created date NULL,
	author_id int8 NULL,
	CONSTRAINT requests_pk PRIMARY KEY (id),
	CONSTRAINT requests_users_fk FOREIGN KEY (author_id) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS items (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar NOT NULL,
	description varchar NULL,
	available bool NULL,
	owner_id int8 NULL,
	request_id int8 NULL,
	CONSTRAINT item_pk PRIMARY KEY (id),
	CONSTRAINT item_user_fk FOREIGN KEY (owner_id) REFERENCES users(id),
	CONSTRAINT items_requests_fk FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	status varchar NULL,
	item_id int8 NULL,
	booker_id int8 NULL,
	start_time timestamp NULL,
	end_time timestamp NULL,
	CONSTRAINT booking_pk PRIMARY KEY (id),
	CONSTRAINT booking_items_fk FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT booking_users_fk FOREIGN KEY (booker_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS comments (
	text varchar NULL,
	item_id int8 NULL,
	author_id int8 NULL,
	create_date timestamp NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (id),
	CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT comments_users_fk FOREIGN KEY (author_id) REFERENCES users(id)
);




